### ISSUE TITLE
I want to add the solution of this problem statement

### ISSUE THREAD

**Issue by yashhh-03** [Git-For-Geeks/Competitive_Programming#2]
Hello,
I would like to do this task could you assign me this task.

**Comment by geeks-for-geeks-rcoem** [comment]
@yashhh-03 Which problem do you want to solve?

**Comment by geeks-for-geeks-rcoem** [comment]
@yashhh-03 You can add the Solution
Follow the Guidelines in ReadMe.md file 

Happy Hacking !!
