### ISSUE TITLE
Solution for integer to roman.

### ISSUE THREAD

**Issue by MinalGhate** [Git-For-Geeks/Competitive_Programming#4]
Hey
I would like to add solution for integer to roman in java language.

**Comment by Kush-munot** [comment]
Go Ahead @MinalGhate !!
Make sure that you create a file named as yourname.cpp or any other language you are comfortable with and submit the solution in the respective folder.

If you have any doubts feel free to ask them on the group.
We wish you best luck !!

**Comment by MinalGhate** [comment]
> Go Ahead @MinalGhate !! Make sure that you create a file named as yourname.cpp or any other language you are comfortable with and submit the solution in the respective folder.
> 
> If you have any doubts feel free to ask them on the group. After you have made a Pull Request Please comment here for fast merging We wish you best luck !!

Done 👍
