### ISSUE TITLE
Integer to Roman using C++

### ISSUE THREAD

**Issue by GauravMKedia** [Git-For-Geeks/Competitive_Programming#56]
I want to add the solution to solve Integer to Roman problem using C++ as Java solution is only present.
Please assign it to me.
Also, can you add some more problem to this repository.

**Comment by Sasi0901** [comment]
@GauravMKedia please choose other question because this question is already solved even though it is in other language..

**Comment by GauravMKedia** [comment]
> 

Can you suggest some new issue.
